name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: tinygo/tinygo:0.25.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Go version
        run: go version

      - name: TinyGo version
        run: tinygo version

      - name: Unit test using Go
        run: ls -lah && go test -v ./msgpack/...

      - name: Unit test using TinyGo
        run: tinygo test -v ./...